# Generated by Django 3.2.3 on 2021-06-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=1)),
                ('City', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=500)),
            ],
        ),
    ]
